### ISSUE TITLE
Pysam error: ValueError: invalid reference `chr2`

### ISSUE THREAD

**Issue by sroener** [kircherlab/cfDNA#6]
Hi, 
The script failed for me for some reason, it did generate the intermediate WPS COV tables. I have pasted the error below.  

Activating conda environment: /mnt/disk3/research/madil/kirchirlab/develop_cfDNA/cfDNA/.snakemake/conda/2e6d913f
Using min/max length cutoffs: 120/180
Traceback (most recent call last):
  File "workflow/scripts/WPS/extractFromBAM_RegionBed_WPS_Cov.py", line 107, in <module>
    for read in input_file.fetch(chrom,regionStart-protection-1,regionEnd+protection+1):
  File "csamtools.pyx", line 1059, in pysam.csamtools.Samfile.fetch (pysam/csamtools.c:12490)
  File "csamtools.pyx", line 990, in pysam.csamtools.Samfile._parseRegion (pysam/csamtools.c:11697)
ValueError: invalid reference `chr2`

**RuleException:
CalledProcessError in line 156 of /mnt/disk3/research/madil/kirchirlab/develop_cfDNA/cfDNA/snakefile_WPS.smk:**
Command 'source activate /mnt/disk3/research/madil/kirchirlab/develop_cfDNA/cfDNA/.snakemake/conda/2e6d913f; set -euo pipefail;

File "/mnt/disk3/research/madil/kirchirlab/develop_cfDNA/cfDNA/snakefile_WPS.smk", line 156, in rule_extract_counts_background
File "/home/local/AMC/madil/miniconda3/envs/bio/lib/python3.6/concurrent/futures/thread.py", line 56, in run

_Originally posted by @madil7173 in https://github.com/kircherlab/cfDNA/issues/5#issuecomment-740121334_

**Comment by sroener** [comment]
Should be fixed in develop branch. @madil7173 Please try again whether everything works as expected or not.

**Comment by madil7173** [comment]
Perfect, ran till completion with no errors.

**Comment by madil7173** [comment]
![image](https://user-images.githubusercontent.com/62121743/102376056-1112c400-3f78-11eb-92cc-cf4a2cc335d1.png)
I am wondering if the normalization is different in this newer submit.

**Comment by sroener** [comment]
Good to hear. I hereby close this issue as solved. 

Regarding the normalization, I opened a new issue with the label "question". It would be nice if you could separate your future request if they are unrelated.
